import express from "express";
import { Router } from "express";
import checkAdmin from "../middlewares/checkAdmin.js";
import getAllStudents from "../controllers/Admin-Controllers/getAllStudents.js";
import getAllAttempts from "../controllers/Admin-Controllers/getAllAttempts.js";
import getBestWorstSub from "../controllers/Admin-Controllers/getBestWorstSub.js";
import getAllQuestions from "../controllers/Admin-Controllers/getAllQuestions.js";
const router = Router();
router.get("/getAllStudents", checkAdmin, getAllStudents);
router.get("/getAllAttempts", checkAdmin, getAllAttempts);
router.get("/getbestWorstSub", checkAdmin, getBestWorstSub);
router.get("/getAllQuestions", checkAdmin, getAllQuestions);
export default router;
